export const LANGUAGE_MAP = {
  ar: "Arabic",
  as: "Assamese",
  bn: "Bengali",
  de: "German",
  en: "English",
  es: "Spanish",
  fr: "French",
  gu: "Gujarati",
  hi: "Hindi",
  id: "Indonesian",
  ja: "Japanese",
  kn: "Kannada",
  ko: "Korean",
  ml: "Malayalam",
  mr: "Marathi",
  nl: "Dutch",
  or: "Odia",
  pa: "Punjabi",
  pt: "Portuguese",
  "pt-BR": "Portuguese (Brazil)",
  ru: "Russian",
  ta: "Tamil",
  te: "Telugu",
  ur: "Urdu",
  zh: "Chinese (Simplified)"
};
